// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwLrfxM7n-QjInpe2m7AJnFpTW8OvXFhE',
    appId: '1:253837486153:web:7bef8f2b401b762644b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    authDomain: 'pataslk-app.firebaseapp.com',
    storageBucket: 'pataslk-app.firebasestorage.app',
    measurementId: 'G-72CQ5DWH58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-4msJp_Ssp238uPOwjWLtN-ls-SJp0U',
    appId: '1:253837486153:android:f770ca6b1f1626c344b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    storageBucket: 'pataslk-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczPJCWLezLOcTRLFAj2ih4UzfxQBGtqY',
    appId: '1:253837486153:ios:1347e4fa7834463344b798',
    messagingSenderId: '253837486153',
    projectId: 'pataslk-app',
    storageBucket: 'pataslk-app.firebasestorage.app',
    iosClientId: '253837486153-38crld2nhq6h5trg8spqrcgbj2gj1u13.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGXXIO9A4X_JJ6BMDCVAuyRN52pK-EcSk',
    appId: '1:854767408609:ios:59d7397cfb83f84e2deea0',
    messagingSenderId: '854767408609',
    projectId: 'test-26371',
    storageBucket: 'test-26371.firebasestorage.app',
    iosClientId: '854767408609-hrr54puff57gt4677fe7745s5rht7k95.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtBk61AUzbajG9ZAtRSKDKdR5u2vvq5Tc',
    appId: '1:854767408609:web:bc7394f46476c23c2deea0',
    messagingSenderId: '854767408609',
    projectId: 'test-26371',
    authDomain: 'test-26371.firebaseapp.com',
    storageBucket: 'test-26371.firebasestorage.app',
    measurementId: 'G-GT7J3RRPZN',
  );
}